### ISSUE TITLE
Document data storage format and location

### ISSUE THREAD

**Issue by jidanni** [stephanmahieu/formhistorycontrol-2#10]
Let's say Firefox (and thus Export along with it) is broken and we are
desperate to get our data back out.

Please document what the user can use in such an emergency.
```
$ sqlite3 .mozilla/firefox/*.default-*/storage/default/moz-extension+++*/idb/1148*.sqlite .dump |
perl -nwle "for(/X'([^']+)'/g){my \$n=pack( q(H*), \$_); print \$n;};"|strings -w
```
indeed gets some strings back out, but it's not very pretty.

**Comment by stephanmahieu** [comment]
Totally out of scope.

This github project is all about the add-on, and the API the add-on has to use no longer supports access to sqlite databases.
I am not going to document or support commandline utilities and tools like perl and sqlite. Writing documentation for this is a project in itself, not to mention providing support for different operating systems.

Take a look at my formhistory-export project where this issue is probably more appropriate. Export to csv for example  can easily be added to this java application which automatically makes the export available to almost every OS.
