### ISSUE TITLE
No recovery of text box  - question2answer

### ISSUE THREAD

**Issue by hermann-san** [stephanmahieu/formhistorycontrol-2#103]
**Describe the bug**
not possible to recover text from the question box of this page
https://www.question2answer.org/qa/

**To Reproduce**
1. Go to https://www.question2answer.org/qa/  and register for an account
2. click on create / ask a question
3.  enter some text and try to recover it.

**Expected behavior**
In context menu of form history controller, the editor field text that that text box should be recoverable

**Screenshots**

![Auswahl_037](https://user-images.githubusercontent.com/7679654/82741349-62940100-9d51-11ea-95e4-744240597388.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1
 - Browser Firefox 
 - Version 76

**Additional context**

recovery of small title box is possible.

different issue:  there is a dead link to the FAQ on this page:
https://stephanmahieu.github.io/fhc-home/Manual/KnownIssues/

**Comment by stephanmahieu** [comment]
Dead link (and nearby typo) has been fixed.

**Comment by stephanmahieu** [comment]
This issue is also mentioned in the comments of 25 april 2020 to the [feature-requests](https://formhistory.blogspot.com/2009/05/feature-requests.html) on my blog.

The site question2answer is using a version of the CKEditor framework which uses an iframe. Text entered in the form inside the iframe is not captured by FHC. I will look into this but no promises.

**Comment by stephanmahieu** [comment]
Issue is fixed in FHC release 2.5.6.1.
Can you verify that @hermann-san ?
