### ISSUE TITLE
Firefox crashes during editing settings

### ISSUE THREAD

**Issue by lysathor** [stephanmahieu/formhistorycontrol-2#116]
**Describe the bug**
This is sporadic. When editing Form History Control (II) settings the Firefox window closes without notice.

**To Reproduce**
Sporadically I get Firefox crash: 
1) Go to addons. 
2) Edit Form History Control (II) settings. E.g. change short cuts etc. 
3) Change more settings. The chance is high that Firefox' window disappears. 
4) No crash dialog or warning is shown. In the console you can see 
![grafik](https://user-images.githubusercontent.com/4583286/99302613-e423a200-284f-11eb-9cac-2c71f5cf77fe.png)

**Expected behavior**
The setting should be applied but Firefox should not crash.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4583286/99302613-e423a200-284f-11eb-9cac-2c71f5cf77fe.png)

**Desktop (please complete the following information):**
 - OS: Win 10 x64
 - Browser Firefox 
 - Version 82.0.3

**Comment by stephanmahieu** [comment]
In your screenshots I see only one error that is related to FHC (popup-big.js), a rejected promise. That in itself is a common error that occurs frequently and has to do with the asynchronous events being sent back and forth by FHC that I believe can not be solved or prevented because it is inherit to the way FF handles these event messages. The only thing different here is the "Actor conduits destroyed..." See also issue [1665380](https://bugzilla.mozilla.org/show_bug.cgi?id=1665380) on bugzilla concernig this type of error,

I see the Promise rejected errors very frequently and believe they do no harm nor should they cause any trouble for FF itself. I personally have never experienced the described crashes whilst working with FF and FHC options.

It is likely that the crashes are caused by one of the other plugins where Page Shadow is the main suspect since the errors from this plugin occur just before and after the one error in FHC.

**Comment by stephanmahieu** [comment]
Got no response from @lysathor and received no similar reports or issues.
Closing this issue.
