### ISSUE TITLE
<select> not saved!

### ISSUE THREAD

**Issue by jidanni** [stephanmahieu/formhistorycontrol-2#12]
I discovered a vital part of HTML forms is not being detected: ```<select>```!

```
  <select name="ReasonForlate_35" aria-label=
    "If this report is being filed late, select the reason for filing late">
      <option role="option" value="A">
        Forgot to file
      </option>
      <option role="option" value="B">
        Did not know that I had to file
      </option>...
      <option role="option" value="I">
        Unable to access BSA E-filing system
      </option>
      <option role="option" value="Z">
        Other (Please provide explanation below)
      </option>
    </select>
```
(Seen on [Online FBAR](https://bsaefiling.fincen.treas.gov/NoRegFBARFiler.html)).

In effect, users' gender choice will be lost,
```
[ ]Male
[x]Female
[ ]Other: Explain ______________
```
only their explanation will be saved!

```
Individual's Date of Birth
Year
Month
Day
```
would be saved if they were simple textboxes.
But if they are 1960, 1961... selectors, we end up having to choose them
all over again :-(

City is saved
State is not (because it is a ```<select>``` here on the FBAR form I'm filling out)
ZIP/postal code is saved
Country/Region is not. (```<select>``` again.)

One could say the more easy the form authors try to make it for the user
(by employing ```<select>```), the more harder it becomes for the add-on user.

In fact one could say why are **disabled** items that the user has no
control of like
```
<input name="VersionNumber_20" disabled="disabled" value="1.0" type="text">
```
being saved, but not at the same time saving our ```<select>``` choices?!

**Comment by jidanni** [comment]
Wait! In about:addons we see:
> This extension can also be used as an easy form filler. It will restore text and editor fields as well as **various input controls**. On each submission of a webform, the **state of controls like radio-buttons and check-boxes** are saved. You can autofill textfields and various controls in a web form using either the most used or the last used formhistory data.

So apparently it really is a bug that ```<select>``` is not being saved.
Or, as it says "On each submission ... are saved." (Bug in wording too?)
But I am slowly filling in the miles long tax form. I want the ```<select>```
items saved as I select them. As that final day when I finally click
```<submit>``` will be many moons and power outages from now.

**Comment by stephanmahieu** [comment]
As you already found out selects are only saved when the form is submitted, this also applies to radiobuttons and checkboxes. Another difference with text fields is that only the last state of these type of formelements is saved, so no history is kept (times, used, last used, most often used).

The reason that the state is only stored when the form is submitted, is that the amount of data can be enormous. For technical reasons the state of each individual item in the select list must be stored, so for each item the state selected/not-selected is stored (some selects allow multiple selections).
Since I do not know in advance wether a form on a webpage is going to be submitted or not, I would have to store the state of each and every select/radio/checkbox item on that page the moment the webpage is loaded. That would result in an enormous amount of data being stored, not to mention the negative impact on performance and the size-limits of the underlying datastore.

So regarding the special form elements like select/radio/checkbox and with respect to the idea of this add-on being used as an "easy formfiller": the special form elements  will only be stored when the form is submitted and without history (only the last state for that domain, the previous state is discarded).

So no bug here, it works as designed and I have no intention to change the special form elements behavior.

**Comment by jidanni** [comment]
(I was thinking you might want to only store items that were changed by
the user, at the moment he changes them, be it textboxes or radio buttons...)

(Anyway probably a better strategy for me with the miles long tax form is:
Use Developer Tools: Edit as HTML-> cut -> transform -> paste, then submit.
With the transform stage being done by a program that I write...)

**Comment by coling** [comment]
Forgive me if I'm getting the wrong end of the stick here but I'm not seeing selects being saved or restored (even on submission).

No <select> element is being detected on the page at all (with the show all fields option) and it's certainly not being restored nor saved (if I look at the history manually).

The comment above states:

> As you already found out selects are only saved when the form is submitted, this also applies to radiobuttons and checkboxes.

so I think this is an actual bug? I mean if it's saved on submission it should be restored again next time round right? Using latest version.

**Comment by stephanmahieu** [comment]
Selects, radiobuttons and checkboxes do not show up in the userinterface nor are they displayed using the _Show fields_ option.
When they are saved, only the checked or selected values are saved.

**Comment by coling** [comment]
> Selects, radiobuttons and checkboxes do not show up in the userinterface nor are they displayed using the _Show fields_ option.

Can you clarify what you mean by "not show up in the userinterface". Do you mean when reviewing the saved data through the "Manage History" dialog? Does this mean that the data is saved by the extension but cannot be viewed, modified or deleted via Manage History, nor is it used when selecting a "Fill fields with..." option? If so, then this data literally just sits in the database and is completely inaccessible? I've surely misunderstood but I'm struggling to see how this works! :-)

> When they are saved, only the checked or selected values are saved.

That's fine. That would be all I'd want, but I would very much like for this to be restored again when using a "Fill fields with..." option but this does not seem to be the case?

**Comment by stephanmahieu** [comment]
Restoring of a select should work, can you give me an example of a site where restoring of a selection does not work?
