### ISSUE TITLE
Rich text support for copying to the buffer

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#122]
FHC can perfectly save rich forms, e.g.

A

multiline

comment

with **some** _formatting_.

This gets saved:
```
A<br><br>multiline<br><br>comment<br><br>with <strong>some</strong> <i>formatting</i>.
```

It would be great if it was possible to copy the actual rich data/text, not a text HTML data to the clipboard. Currently when you copy this save field to the clipboard and paste it, you paste **HTML text data** not rich/formatted text.

**Comment by stephanmahieu** [comment]
I am afraid its is not possible to convert HTML to RTF directly, that would require low level access to the clipboard which is not supported. Converting  HTML to RTF and pasting that into the clipboard would have no effect other than that it would display your html example with rtf formatting codes instead of html elements:

```{\rtf1\ansi
A{\pard\par}
{\pard\par}
multiline{\pard\par}
{\pard\par}
comment{\pard\par}
{\pard\par}
with {\b
some
} {\i
formatting
}.
}
```

Only after saving the clipboard content to a file with an .rtf extension and opening it with an editor that supports RTF would it reveal the intended formatting. That would be not different from saving the html snippet to a file and opening that with an editor that supports html or a browser.

And then I have not mentioned the fact that RTF is (or was) a Microsoft proprietary format that might not be so well supported on other platforms besides Windows.

**Comment by birdie-github** [comment]
@stephanmahieu 

Under Linux richly formatted text from such fields can be copied to the buffer and pasted in e.g. LibreOffice while all the formatting gets retained. It works, I don't know how, and it's not Windows.
