### ISSUE TITLE
Manage History discards data

### ISSUE THREAD

**Issue by alexolog** [stephanmahieu/formhistorycontrol-2#139]
**Describe the bug**
"Manage History" truncates the number of entries.

**To Reproduce**
1. Accumulate a long history of entries
2. Click on icon in address bar
3. Select "Manage History"

**Expected behavior**
All the entries get loaded.

**Screenshots**

![image](https://user-images.githubusercontent.com/2112513/131044569-29aa989d-66c6-45f4-a854-e6a0b25547c8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 92b8 (but previous versions behave the same)

**Comment by shocked-gamer** [comment]
it's not really a bug, it's expected behavior. it doesn't delete anything unless you delete them or the set number of days has passed, it would consume too much time in order to display them all (seeing you have more than 8000 entries still stored.) in the toolbar dialog. opening the dialog from the FF toolbar menu should display this message. click the white paper-pencil icon next to the settings icon to open the advanced dialog in order to display the whole entries.

![Untitled](https://user-images.githubusercontent.com/33640073/134394835-e361c3e6-7665-4427-aa58-7e8fcd9290ee.png)

**Comment by alexolog** [comment]
Unfortunately, when I uninstalled and reinstalled the addon, the form history was lost (I forgot to back it up) so I cannot check with 8K entries.

However, with 387 entries, there is no such icon visible on the dialog:

![image](https://user-images.githubusercontent.com/2112513/134417448-f2ca8e4b-8db2-4e46-b4e6-b2f216e39df5.png)

**Comment by shocked-gamer** [comment]
yes, upon removal it removes all data. the reason the dialog opened without any warning messages, is because 387 entries are a very small number and it can display it easily.
if Stephan can improve the code and make it so ALL entries can be displayed, i think it could lead to extension and browser instability and lagging.

**Comment by alexolog** [comment]
> click the white paper-pencil icon next to the settings icon to open the advanced dialog in order to display the whole entries.

This issue is about the "advanced dialog" **_ALSO_** not displaying the whole entries.
The same error message pops up in the advanced dialog.

**Comment by stephanmahieu** [comment]
The small popup window is limited in resources by the browser, when trying to show  too much data (or not so much data but on a slow computer) the browser will step in and report an unresponsive script.
The advanced dialog has no resource limitation so it will retrieve and show data much faster, if however it takes more than 5 seconds to retrieve all data FHC will stop retrieving the rest and show what is has retrieved so far.

In either case, if FHC does not abort the retrieval after 5 seconds the browser will kick in and alert the user about an unresponsive script.

So my advice would be, as the warning-popup suggests, to cleanup your formhistory data and minimize the amount of data (or buy a faster computer ;-) ). I am testing regularly with a dataset containing almost 5000 items which is shown well under 3 seconds, so 8000 might be just a bit too much.
