### ISSUE TITLE
UX problem loading and unable to display all data

### ISSUE THREAD

**Issue by madduck** [stephanmahieu/formhistorycontrol-2#142]
When I open the FHC dialog from the toolbar, the first thing I am told is that it's Loading:
![image](https://user-images.githubusercontent.com/195073/157630016-a5f5dc24-91dc-449e-8612-f37695ab8a36.png)
I cannot interact (all I want is to copy the top-most entry) for about 25 long seconds. I also must take care not to click anywhere, or the popup disappears and I'd have to restart.

Then, I am finallly told that there is too much data:
![image](https://user-images.githubusercontent.com/195073/157630702-c59bf78c-9d3e-4d38-81e7-179934789bf3.png)
So after 25 seconds of waiting, I have to click away that dialog, and only then I can do what I came here to do. This isn't a very good user experience, I find.

Note that I am told to use the advanced window instead, but it has the exact same issue.

If possible, could FHC let me interact with the data as it's loading? And instead of popping up a modal warning, maybe show the warning in a non-obtrusive way?

Yes, I keep history for a year, which is a long time, but there is really no reason I shouldn't be able to do this.

I am on Firefox 96 on Linux.

**Comment by shocked-gamer** [comment]
50.000+ entries seems too much. i think the developer didn't made the addon with the purpose of displaying too much data so fast.

**Comment by stephanmahieu** [comment]
Indeed 56.000 + items is way too much for the Dialog that opens from the toolbar. Mozilla limits the resources for those popups substantially, not much I can do about that. When opening the main dialog from the right click menu it should load fine.

**Comment by madduck** [comment]
@stephanmahieu as I wrote in the issue, the "advanced window" has the same problem.

**Comment by stephanmahieu** [comment]
The advanced window seems to be limited to about 53529 items in your case. I am afraid you run into the limitations of available resources and the time restrictions to process that amount by the browser.
The table used to display the data is a jquery plugin. There is probably another way to dynamically load only the data you see at the time but that would require a major update to the current architecture of this plugin.

Since this is a very rare usecase (and surely you have good reasons wanting to keep that many items in your history) I am not inclined to put in the many hours needed to support (what I want to call) an excessive amount of history items.

**Comment by stephanmahieu** [comment]
Starting with v2.5.10.0 the FHC dialog from the toolbar uses deferred rendering. That should allow for more entries to be loaded. Can you confirm @madduck ?

Also FHC uses the latest major update of DataTables, maybe it allows for more entries in the advanced window too.
