### ISSUE TITLE
Suggestion.  FHC could improve the user experience for websites that do not handle the back button, undo or form-load properly.

### ISSUE THREAD

**Issue by the-moog** [stephanmahieu/formhistorycontrol-2#150]
This would be done by using the URL as well as an optional session key, either part of that URL or a given site cookie date.

**Is your feature request related to a problem? Please describe.**
I had an issue where a website did not properly respect the back button, which was accidentally used during a form edit.
Both the prior version and the edit were lost.  As the back created a new load and the subsequent forward created a new form.

**Describe the solution you'd like**
FHC should preserve the prior contents of the form on load, not just on save. 
It would then have a before, after state. The form is saved only if load state is not the same as submit state.

**Describe alternatives you've considered**
No idea

**Additional context**
None

**Comment by stephanmahieu** [comment]
You can tweak the parameters which cause a new history entry to be created instead of updating the current entry (with possibly an empty form).
You can set an interval to force a new entry (default 10 minutes) and interesting for your case a character length. If the length changes more than 500 character (default) also a new entry is created, you can set this to a much smaller length.
