### ISSUE TITLE
Most form history entries lack URL

### ISSUE THREAD

**Issue by NicolasMICAUX** [stephanmahieu/formhistorycontrol-2#152]
**Describe the bug**
Most form history entries lack URL, which is not practical when for example trying to see where you inputted your adress.
![image](https://github.com/stephanmahieu/formhistorycontrol-2/assets/72763959/b3d531d5-84fd-40a2-bd5a-4ebb343d4529)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 22.04
 - Browser : Chrome Version 114.0.5735.198 (Build officiel) (64 bits)

**Comment by stephanmahieu** [comment]
This behavior is by design. Take for example a field named "telephone", it is very likely this field is used on numerous websites. When filling a field named telephone with previously recorded data it does not make sense to offer only telephone no's from the same website/url. That is why Mozilla itself and also this extension does not record the URL for standard input fields.

**Comment by NicolasMICAUX** [comment]
Interesting thank you for answering
The use case for me was to change my email address on every website where I have previously inputted it, for example.
