### ISSUE TITLE
Loading animation blocks the whole UI, including the top right buttons.

### ISSUE THREAD

**Issue by YousufSSyed** [stephanmahieu/formhistorycontrol-2#167]
On Firefox on my M1 MacBook Pro it takes a good 15 - 30 secs to load. The loading animation blocks the whole UI so I can't open the addon in a new window or open the settings until it finishes.

**Comment by stephanmahieu** [comment]
You probably have a large no of entries collected over time. The small FHC popdown (left-click on the Form History Control icon in the toolbar) is impacted the most since it is limited in resources by the browser and sometime me never finish loading. When opening the regular FHC popup dialog it may either take long (max 30 sec) and show you a warning when not all entries coueld be loaded within time. The only way to fix this is to do a cleanup and reduce the amount of entries.

**Comment by stephanmahieu** [comment]
Which OS are you using? While the load animation is showing, it normally does not block any UI elements of the browser.

**Comment by YousufSSyed** [comment]
I'm gonna close this issue since I've been checking it every now and then and it seems like its gone.
