### ISSUE TITLE
Restoring Text into a TextArea on Reddit.com Is Broken

### ISSUE THREAD

**Issue by stevej-algoteer** [stephanmahieu/formhistorycontrol-2#175]
**Describe the bug**
On reddit.com, in a textarea, when you try to restore text, the textarea's borders turn red and the background turns to yellow for a few seconds, then those go away and nothing else happens. No text is pasted into the textarea. 

**To Reproduce**
1. Go to reddit.com.
2. Press "+ Create" to write a new post.
3. Enter some multi-line text in the textarea.
4. Make sure that Form History Control (II) has saved the text.
5. Right-click in the textarea and select _Form History Control (II)→Restore editor field→(select some saved text)_.

**Expected behavior**
The text from the selected entry should be pasted into the textarea.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 127.0.2

**Comment by stephanmahieu** [comment]
Restoring formhistory data into a fields will not always work. This is due to the fact that many sites nowadays use a combination of custom field(s) (some of which are hidden) and javascript to give the user maximum functionality. That makes it sometimes impossible for a peace of code (aka the FHC plugin) to inject the text into the proper field. And your lucky if saving text input does work because that is often also a pita.
Alas Reddit is one of those sites where injecting does not work properly (facebook another example). In these cases copying the formhistory text to the clipboard and pasting it is the best alternative.
