### ISSUE TITLE
Only some text blocks saved.

### ISSUE THREAD

**Issue by abalter** [stephanmahieu/formhistorycontrol-2#178]
I was filling out an [Eversign](https://eversign.com/) form when I accidentally moved away from the page. When I returned, only a few of the text blocks had been saved in the extension, and which ones was kind of random.

Are there particular settings you recommend?

**Comment by stephanmahieu** [comment]
This is probably due to the fact that many sites nowadays use a combination of custom field(s) (some of which are hidden) and javascript to give the user maximum functionality. That makes it sometimes impossible for a peace of code (aka the FHC plugin) to capture text you enter in fields or forms.
What may be the case here is that the text blocks you enter are input into the same field before being automatically moved (added) to a wysiwyg field. If that is the case it may help to lower the "Save a new version when last version is older than" interval in ([miscellaneous settings](https://stephanmahieu.github.io/fhc-home/Manual/manual/#miscellaneous))
