### ISSUE TITLE
Option to register context menu in "editable" context rather than "all"

### ISSUE THREAD

**Issue by ssokolow** [stephanmahieu/formhistorycontrol-2#34]
I go to a lot of trouble to use `userChrome.css` to keep my context menu from getting really cluttered by various unwanted Mozilla brainstorms as well as the various addons I prefer to access through other means... and I have yet to find a way to do that with enough nuance to narrow the contexts in which an entry appears without removing it entirely.

I'd really prefer it if Form History Control's submenu only appeared when I right-clicked on a form element, rather than anywhere in the page. (After all, the *context* menu is supposed to be contextual.)

Please consider at least adding a config option to register your context menu entries with `contexts: ["editable"],` rather than `contexts: ["all"],`.

**Comment by stephanmahieu** [comment]
The menu does serve a purpose when not used from a form element, for instance it is possible to display formfield-info for all fields on a page or just fill all formfields on the page. When the contextmenu is opened from a formfield, fill formfield will only act upon the active formfield. For both use cases (all fields and current field) you can use the same contextmenu.

Further more, using "editable" only works reliable for formfields (input, textarea) and not so much for  divs/iframes/body/html with contenteditable style or desginmode=on, that is also a reason why I chose to go with ["all"].

I will keep the suggestion for a configurable option in the back of my mind, the menu configuration is a PITA because of the different limitations (max items shown) depending on where the context menu is opened.
