### ISSUE TITLE
Records Facebook comments as you type but loses them when you press return

### ISSUE THREAD

**Issue by robertinventor** [stephanmahieu/formhistorycontrol-2#38]
Example, I type this into a Facebook comment:

> Test comment on facebook

![image](https://user-images.githubusercontent.com/8162860/46502199-7e1a6300-c81f-11e8-9529-d141d871e4da.png)

Then press return to post the comment and the field changes to show:
![image](https://user-images.githubusercontent.com/8162860/46502273-ab671100-c81f-11e8-8c28-4c7c32a84cc3.png)

I can fix this to some extent by setting it to record what I type every minute and every ten characters typed but I can still lose but lose up to last 10 characters of the comment (if made in last minute before pressing return) in a Facebook comment as well as having dozens of entries for each comment if it is a long one.

It's already useful  but if this can be fixed will be even more useful. I mainly want it for situations where someone deletes a post that I have made many comments on, as the comments are then deleted from the Facebook activity log. (I often write up these comments as blog posts). 

Thanks for a great plugin :).

**Comment by stephanmahieu** [comment]
This is probably caused by the fact that facebook (javascript) moves the content of the field to another location when you hit the post button. This is perceived by the add-on as a regular update and stored in the same manner as updates triggered by the user typing.

**Comment by robertinventor** [comment]
Okay. Is a fix possible? One simple suggestion, to set it to never store updates that erase the content of a field? Or to set a minumum number of characters of content for it to store it as an update?

**Comment by stephanmahieu** [comment]
After I have done some investigation I might be able to come up with a solution.

**Comment by robertinventor** [comment]
Thanks!

**Comment by stephanmahieu** [comment]
The cause of this issue is the fact that when you have completed and published your message, the input field is emptied and prepared for the next message (tweet) you might want to publish. Because the input field remains the same, it is perceived by FHC as a regular update en the corresponding formhistory entry is updated accordingly.
More conversation type applications suffer from this very same behavior like for instance Twitter and WhatsApp Web.

I do not think this is really a serious issue given the fact that that the main purpose of storing formhistory (and that is especially the case for multiline fields), is saving it to protect you from loosing your hard work in  case disaster strucks. If you successfully published the message there is no longer a need for restoring the very same message.

I Also think that there is no viable solution for detecting the difference in emptying input field caused by normal user editing or successfully publishing a message.
