### ISSUE TITLE
Restore Editor Field doesn't respect the field ID

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#42]
This can be easily reproduced on GitHub. Create a few tickets then create a new empty one, right click in the ticket title, "Restore Editor Field" and you'll see the entries for the "body" element, not for the "title" element.

![bug](https://user-images.githubusercontent.com/4958603/46799309-edd3a500-cd6d-11e8-8444-3d9c6a4bfa0f.png)

**Comment by stephanmahieu** [comment]
This restoring editor field might be a bit confusing.

First of all, the _Restore editor field_ only acts upon multiline editor fields and the title element is actually an input field. So if you try to restore a field using this restore editor field option you only see formhistory for multiline fields.

One of the reasons this distinction is made is because (single line) text input fields are never bound to a particular host or page. This type of field is considered to be generic, so if you have for instance a field called email or phone you can re-use the fieldvalue on any page containing a formfield with the same name. This is also exactly how the browser itself stores the formhistory.

Multiline/editor fields are almost never generic and only useful in the context of the page where it was used. So for these type of fields the url (host) of the page is stored along with its contents.

Thus when you choose to restore using the _Fill fields..._ option this add-on will try to restore all multiline fields where both fieldname and host or URL matches, and will restore all text input fields for matching fieldnames only.
When using the Restore editor field option, only the multiline type fields are given as option where the hostname matches plus the most recent entries not matching the hostname. If you invoke this option from a particular editor field, the add-on will try to match the fieldname as well.
