### ISSUE TITLE
Make it work with gitlab WebIDE ?

### ISSUE THREAD

**Issue by bflorat** [stephanmahieu/formhistorycontrol-2#51]
Not really a bug but a limitation : 
This plugin doesn't work for Gitlab webIDE (when editing a .md file for instance). None history stored. 

Gitlab WebIDE doesn't use regular text field but some kinds of divs : 

![image](https://user-images.githubusercontent.com/203516/59610783-5ef80300-911a-11e9-955f-1e68399c8d1a.png)

Do you think your plugin could work somedays ?

Environment : Debian 9 / Firefox 60 / GitLab Community Edition 11.7.6

Works great for the others websites, thanks for the great work

**Comment by stephanmahieu** [comment]
Gitlab WebIDE uses embeddable code editor [ACE](https://ace.c9.io/) which is a PITA. I myself use Splunk a lot and they also use [ACE](https://ace.c9.io/).
What happens in ACE is that you actually type into a texarea field and that content is almost immediately moved to a div. The FHC-addon detects and monitors the textarea field but this field is empty most of the time so nothing gets saved. The div where the actual content ends up can't be detected by the plugin because it looks like any other non editable div. It is the javascript from ACE that does the magic and renders the FHC-addon useless.

Right now I see no generic way in solving this problem, other than to detect this special case and try to find the div where the actual content ends up.
A somewhat similar issue is facebook messenger where the content is inside a nested div structure. Here the content is saved okay but when restored it is falsely restored in the content-editable root div instead of one of the the nested div's within.

**Comment by stephanmahieu** [comment]
This issue is fixed long time ago.
