### ISSUE TITLE
Pressing keyboard shortcuts overwrites current form with no way to undo

### ISSUE THREAD

**Issue by nyanpasu64** [stephanmahieu/formhistorycontrol-2#56]
I was writing a long post in Firefox in a SMF forum (which uses Alt+Shift+P to preview) when I accidentally pressed Alt+Shift+something else. Form History Control overwrote my entire post, with no way to undo.

Is it possible to make "overwriting current form" an undoable process?

And https://github.com/stephanmahieu/formhistorycontrol-2/issues/48 is it possible to "disable" shortcuts by doing nothing whenever they're pressed?

**Comment by stephanmahieu** [comment]
Disabling shortcuts is now available in the 2.4.0.0 release

**Comment by stephanmahieu** [comment]
Normally filling fields will not overwrite existing text.
What happened here is probably due to the special handling of posts on that page: text entered in an input field is moved by the page-handler to a special presentation field. The actual input field is thus almost always empty and that meant that filling that field by the FHC add-on did not overwrite anything.

**Comment by stephanmahieu** [comment]
Disable shortcut keys has been added, The issue about overwriting can not be fixed with an undo so I will close this issue.
