### ISSUE TITLE
Form History Control "Host" field sometimes blank

### ISSUE THREAD

**Issue by jidanni** [stephanmahieu/formhistorycontrol-2#6]
In Form History Control the rightmost column is called Host.
We see Github.com listed there just fine.
But some sometimes the Host field is blank!

Choose "Online Form" on
https://bsaefiling.fincen.treas.gov/NoRegFBARFiler.html

This should lead to
https://bsaefiling1.fincen.treas.gov/lc/content/xfaforms/profiles/htmldefault.html

Fill out some fields.
For this site the Host field is blank!

**Comment by shocked-gamer** [comment]
yes i confirm that sometimes the "Host" field is blank.

**Comment by stephanmahieu** [comment]
The host field is only stored for multiline edit fields only. If the field is of type (text) input, no host information is stored. This is the way mozilla stores the formhistory for this type of field.
The reason behind this is that usually text input fields contain information that is useful across domains like name and address information, while multiline formhistory fields are most likely only ever restored on the domain it came from.
Take for instance an address field, if this was linked to a host name and you encountered this field on another domain should we store this as a new field with the same name and value but with a different host? In that case it would be better to create a one-to-many relation where a field with the same name and content is used on different domains at different points in time. I decided not to implement it that way because it adds a level of complexity with very little added value.

**Comment by jidanni** [comment]
Holy smokes who would have ever guessed it was the number of lines
involved.

Anyways I thought Firefox already had Form Filler features that were
built in and often fill in my email for me nicely.

So I was thinking of using formhistorycontrol for the non general case
where I am filling in a whopping "FBAR" account reporting form where I
have to add details of up to 25 accounts and it all must be in one
session.

> One-time submission
> 
> The online FBAR form does not allow you to save your progress during form completion as it is designed
> to benefit filers who are ready to file the FBAR today. If you have gathered all information needed to
> complete and submit the FBAR in a one-sitting, then the online form might be right for you...
> 
> System requirements
> 
> Active Internet Connection
> You must maintain an active internet connection throughout form preparation and submission. If at any
> point prior to submission you lose internet connection, all data entered in the form will be lost and you
> will be required to start over, as there is no option to save prior to submission when using the online
> FBAR form. 

For such forms I specifically **do not** want data leaking back and
forth throughout Firefox just due to matching form control names.

And later I wish to specifically export and import data from and to
formhistorycontrol via database slices specifically using the site name.

Just like cookies always have a domain field, it would be great if there
were an option to set the limit to remember the site name to 'always' at
least for specific sites.

**Comment by stephanmahieu** [comment]
Just for the record, Firefox never had any formfilling capabilities, just autocomplete (driop down) and that never uses the host but only the name (or id) of the field.
