### ISSUE TITLE
After filling out the add-on, the field remains highlighted forever

### ISSUE THREAD

**Issue by wvxwxvw** [stephanmahieu/formhistorycontrol-2#70]
After filling out the add-on, the field remains highlighted forever

I used padding and then edited the text in field.
![2019 12 29_175025](https://user-images.githubusercontent.com/13194155/71558409-0cea4f80-2a64-11ea-84ed-a6f35b550f03.jpg)
Then I sent a comment.
![2019 12 29_175109](https://user-images.githubusercontent.com/13194155/71558427-43c06580-2a64-11ea-9a36-39cd37343f03.jpg)

This is not right. The backlight should disappear immediately after the user sets the cursor in the editable field. Not to mention updating the page.

**Comment by stephanmahieu** [comment]
You make it sound like this benavior is a bug, I consider the proposed change a feature request.

**Comment by wvxwxvw** [comment]
As you say. But I think it's a mistake. Depending on the page's styles, this feature (as you think) can make the field unreadable.

**Comment by stephanmahieu** [comment]
If you auto-fill a field, some additional html-code is added to the page to highlight the field. This is in response to an action performed by the user and initiated from the add-on.
What you propose is quite the opposite, some action performed on the page itself should trigger an action by the add-on so it can remove the highlight. I see no way to accomplish such a trigger from the internet page since each internet page has its own way of handling user-interaction.

**Comment by wvxwxvw** [comment]
Got it. Replace it with contour highlighting, instead of highlighting the entire field.

**Comment by stephanmahieu** [comment]
That might work :-)

**Comment by stephanmahieu** [comment]
On second thought, I had contour highlighting before but ditched that because sometimes it affected the layout of a page too much. In order to display a colored box around the field the field-border has to have a certain thickness. So if the field has no border yet, setting a thickness would make the field become larger which would affect the layout. If the field already has a border changing its width and/or its color also can have an undesired affect on the overall layout. Alternatively one could overlay a floating colored box which would not affect the existing layout but that causes other complications like resizing or shielding the underlying field from being clicked.

Changing the background color is the most simple thing to do and has the least effect on the layout of a page. What I can do is adjust the background color based on the existing color so the contrast between the text and the background color stays intact and text remains easy readable.

**Comment by wvxwxvw** [comment]
Or add a marker (icon) in the lower right corner of the field? As it was before with one extension for editing the content of input fields in an external editor.

By the way, here's another idea for expanding the functionality - an external editor specified by the user, such as Notepad++. Only not bound to standard paths, but with an arbitrary path of the executable file.

**Comment by stephanmahieu** [comment]
Now available in release 2.5.0.0.
