### ISSUE TITLE
Need to press the Export button before tallies are filled in

### ISSUE THREAD

**Issue by jidanni** [stephanmahieu/formhistorycontrol-2#8]
When doing Export, the user sees two empty "-" tallies,
![kfs](https://user-images.githubusercontent.com/1230959/35195741-d6f5820c-ff02-11e7-819e-21a023cfe285.jpg)
At this point the user thinks 'Gosh, looks like I am out of luck.'
It turns out one needs to press the Export button before they are filled in.
It would be best to only show lines with numbers.

**Comment by stephanmahieu** [comment]
Fixed in version 2.2.0.0 just released a few minutes ago. Export is now immediately executed when the popup is displayed, so the tallies should always display a value (when export finishes). In addition added a note explaining the download link.
![export](https://user-images.githubusercontent.com/11545961/44907315-c1148280-ad17-11e8-81f5-e99439abd821.png)
